.nh
.TH "PB-AUTH-LOGOUT" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-auth-logout - Revoke and remove the active client session


.SH SYNOPSIS
\fBpb auth logout [flags]\fP


.SH DESCRIPTION
Revoke and remove the active client session

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for logout

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-auth(1)\fP
