.nh
.TH "PB-AUTH" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-auth - Manage Paperboat sign-in


.SH SYNOPSIS
\fBpb auth [flags]\fP


.SH DESCRIPTION
Manage Paperboat sign-in

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for auth


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-auth-login(1)\fP, \fBpb-auth-logout(1)\fP, \fBpb-auth-status(1)\fP, \fBpb-auth-switch(1)\fP
