.nh
.TH "PB-ACCESS-TUNNEL" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-access-tunnel - Open private TCP access through stable hostd


.SH SYNOPSIS
\fBpb access tunnel  [flags]\fP


.SH DESCRIPTION
Open private TCP access through stable hostd

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tunnel

.PP
\fB--json\fP[=false]
	print canonical JSON

.PP
\fB--listen\fP="127.0.0.1:0"
	literal-loopback listen address


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-access(1)\fP
