.nh
.TH "PB-AUTH-SWITCH" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-auth-switch - Show dashboard enrollment instructions


.SH SYNOPSIS
\fBpb auth switch [flags]\fP


.SH DESCRIPTION
Show dashboard enrollment instructions

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for switch

.PP
\fB--json\fP[=false]
	print enrollment instructions as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-auth(1)\fP
