.nh
.TH "PB-CONFIG-TEAM-DEFAULT-ADOPT" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-team-default-adopt - Adopt a team default using your provider access


.SH SYNOPSIS
\fBpb config team-default-adopt  [flags]\fP


.SH DESCRIPTION
Adopt a team default using your provider access

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for team-default-adopt

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
