.nh
.TH "PB-CONFIG-CUSTOMIZE-VALIDATE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-customize-validate - Validate preferences without executing any action


.SH SYNOPSIS
\fBpb config customize validate [flags]\fP


.SH DESCRIPTION
Validate preferences without executing any action

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for validate

.PP
\fB--json\fP[=false]
	print machine-readable JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config-customize(1)\fP
