.nh
.TH "PB-CONFIG-SET" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-set - Set a local configuration value


.SH SYNOPSIS
\fBpb config set   [flags]\fP


.SH DESCRIPTION
Set a local configuration value

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
