.nh
.TH "PB-CONFIG-TEAM-DEFAULT-SET" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-team-default-set - Set a team's default pull repository


.SH SYNOPSIS
\fBpb config team-default-set   [flags]\fP


.SH DESCRIPTION
Set a team's default pull repository

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for team-default-set

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
