.nh
.TH "PB-CONFIG-STATUS-BAR-RESET" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-status-bar-reset - Restore status-bar defaults


.SH SYNOPSIS
\fBpb config status-bar reset [flags]\fP


.SH DESCRIPTION
Restore status-bar defaults

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for reset

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config-status-bar(1)\fP
