.nh
.TH "PB-CONFIG-FORCE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-force - Force a scoped configuration direction


.SH SYNOPSIS
\fBpb config force   [path] [flags]\fP


.SH DESCRIPTION
Force a scoped configuration direction

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for force

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--yes\fP[=false]
	confirm the force operation


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
