.nh
.TH "PB-DAEMON-SERVICE-INSTALL" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-daemon-service-install - Install Paperboat daemon as the current-user service


.SH SYNOPSIS
\fBpb daemon service install [flags]\fP


.SH DESCRIPTION
Install Paperboat daemon as the current-user service

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--config\fP=""
	configuration file path

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--server\fP=""
	Paperboat server URL


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences


.SH SEE ALSO
\fBpb-daemon-service(1)\fP
