.nh
.TH "PB-DAEMON" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-daemon - Paperboat endpoint daemon


.SH SYNOPSIS
\fBpb daemon [flags]\fP


.SH DESCRIPTION
Paperboat endpoint daemon

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB--config\fP=""
	configuration file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for daemon

.PP
\fB--server\fP=""
	Paperboat server URL


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-daemon-device-guard(1)\fP, \fBpb-daemon-run(1)\fP, \fBpb-daemon-service(1)\fP
