.nh
.TH "PB-DAEMON-SERVICE-STATUS" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-daemon-service-status - Show Paperboat daemon current-user service status


.SH SYNOPSIS
\fBpb daemon service status [flags]\fP


.SH DESCRIPTION
Show Paperboat daemon current-user service status

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	configuration file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	Paperboat server URL


.SH SEE ALSO
\fBpb-daemon-service(1)\fP
