.nh
.TH "PB-DOCTOR" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-doctor - Check Paperboat connectivity and readiness


.SH SYNOPSIS
\fBpb doctor [machine] [flags]\fP


.SH DESCRIPTION
Check Paperboat connectivity and readiness

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for doctor

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--repair\fP[=false]
	repair Paperboat-owned local dependencies


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP
