.nh
.TH "PB-ENV-VAULT-REMOVE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-vault-remove - Remove this device's local ENV vault custody


.SH SYNOPSIS
\fBpb env vault remove [flags]\fP


.SH DESCRIPTION
Remove this device's local ENV vault custody

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--confirm\fP=""
	exact confirmation phrase: REMOVE LOCAL ENV 

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env-vault(1)\fP
