.nh
.TH "PB-ENV-ROTATE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-rotate - Rotate personal ENV scope keys while preserving values


.SH SYNOPSIS
\fBpb env rotate [flags]\fP


.SH DESCRIPTION
Rotate personal ENV scope keys while preserving values

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rotate

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env(1)\fP, \fBpb-env-rotate-cancel(1)\fP
