.nh
.TH "PB-ENV" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env - Manage ENV Injection for connected hosts


.SH SYNOPSIS
\fBpb env [flags]\fP


.SH DESCRIPTION
Manage ENV Injection for connected hosts

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for env


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-env-grants(1)\fP, \fBpb-env-host(1)\fP, \fBpb-env-list(1)\fP, \fBpb-env-rotate(1)\fP, \fBpb-env-set(1)\fP, \fBpb-env-team(1)\fP, \fBpb-env-unset(1)\fP, \fBpb-env-vault(1)\fP
