.nh
.TH "PB-ENV-TEAM-ROTATE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-team-rotate - Rotate an encrypted ENV team key while preserving its values


.SH SYNOPSIS
\fBpb env team rotate  [flags]\fP


.SH DESCRIPTION
Rotate an encrypted ENV team key while preserving its values

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--confirm\fP=""
	exact confirmation phrase: ROTATE ENV TEAM 

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rotate

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env-team(1)\fP
