.nh
.TH "PB-EXEC" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-exec - Execute an exact command on a machine


.SH SYNOPSIS
\fBpb exec  [flags] -- \fP


.SH DESCRIPTION
Execute an exact command on a machine

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--cwd\fP=""
	absolute remote working directory

.PP
\fB--env\fP=[]
	remote environment name=value

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for exec

.PP
\fB--json\fP[=false]
	emit paperboat.exec-event/v1 JSON Lines

.PP
\fB--pty\fP[=false]
	allocate a remote PTY

.PP
\fB--timeout\fP=0s
	remote execution timeout

.PP
\fB--transport\fP=""
	peer transport: a, d, q, w, or r


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP
