.nh
.TH "PB-ENV-VAULT-RESUME" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-vault-resume - Reconcile an interrupted vault publication


.SH SYNOPSIS
\fBpb env vault resume [flags]\fP


.SH DESCRIPTION
Reconcile an interrupted vault publication

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for resume

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env-vault(1)\fP
