.nh
.TH "PB-INBOX-REQUESTS" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-inbox-requests - List team file requests


.SH SYNOPSIS
\fBpb inbox requests [flags]\fP


.SH DESCRIPTION
List team file requests

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for requests

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-inbox(1)\fP
