.nh
.TH "PB-INBOX-DECLINE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-inbox-decline - Decline an exact team file request


.SH SYNOPSIS
\fBpb inbox decline  [flags]\fP


.SH DESCRIPTION
Decline an exact team file request

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--generation\fP=0

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for decline

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-inbox(1)\fP
