.nh
.TH "PB-INBOX-POLICY" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-inbox-policy - Show or update team file acceptance


.SH SYNOPSIS
\fBpb inbox policy [manual|automatic] [flags]\fP


.SH DESCRIPTION
Show or update team file acceptance

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for policy

.PP
\fB--json\fP[=false]

.PP
\fB--receipt-email\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-inbox(1)\fP
