.nh
.TH "PB-MACHINE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-machine - Manage machines


.SH SYNOPSIS
\fBpb machine [flags]\fP


.SH DESCRIPTION
Manage machines

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for machine


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-machine-add(1)\fP, \fBpb-machine-availability(1)\fP, \fBpb-machine-capabilities(1)\fP, \fBpb-machine-list(1)\fP, \fBpb-machine-rename(1)\fP, \fBpb-machine-revoke(1)\fP
