.nh
.TH "PB-MACHINE-AVAILABILITY" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-machine-availability - Set machine sleep availability


.SH SYNOPSIS
\fBpb machine availability  [flags]\fP


.SH DESCRIPTION
Set machine sleep availability

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for availability

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--mode\fP=""
	availability mode: allow-sleep or keep-awake

.PP
\fB--yes\fP[=false]
	confirm keep-awake power behavior


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-machine(1)\fP
