.nh
.TH "PB-RESOLVE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-resolve - Resolve a peer device IP, port forwardings and tags over gRPC IPC


.SH SYNOPSIS
\fBpb resolve  [flags]\fP


.SH DESCRIPTION
Resolve a peer device IP, port forwardings and tags over gRPC IPC

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for resolve

.PP
\fB--json\fP[=false]
	output JSON format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP
