.nh
.TH "PB-TEAM-LIST" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-list - List teams


.SH SYNOPSIS
\fBpb team list [flags]\fP


.SH DESCRIPTION
List teams

.PP
List teams visible to the signed-in account and their basic state. Select one with pb team get to inspect its current generation and grants.

.PP
Teams use explicit membership and resource grants. Membership alone does not grant device use, ENV values, previews, or tunnels. Mutations use the current team generation to reject stale edits; read pb team get before retrying a conflicting change.

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team(1)\fP
