.nh
.TH "PB-TRANSFER-DESTINATION" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-transfer-destination - Show the default transfer destination


.SH SYNOPSIS
\fBpb transfer destination [flags]\fP


.SH DESCRIPTION
Show the default transfer destination

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for destination

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--session\fP=""
	terminal session ID for a session-specific destination


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-transfer(1)\fP, \fBpb-transfer-destination-clear(1)\fP, \fBpb-transfer-destination-set(1)\fP
