.nh
.TH "PB-TUNNEL-CONNECTOR" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-tunnel-connector - Manage tunnel connectors


.SH SYNOPSIS
\fBpb tunnel connector [flags]\fP


.SH DESCRIPTION
Manage tunnel connectors

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for connector


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--ephemeral\fP[=false]
	use the temporary preview lifecycle

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-tunnel(1)\fP, \fBpb-tunnel-connector-add(1)\fP, \fBpb-tunnel-connector-drain(1)\fP, \fBpb-tunnel-connector-list(1)\fP, \fBpb-tunnel-connector-revoke(1)\fP
