.nh
.TH "PB-TEAM-MACHINE-UNSHARE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-machine-unshare - Withdraw the team's grants while retaining personal ownership


.SH SYNOPSIS
\fBpb team machine unshare   [flags]\fP


.SH DESCRIPTION
Withdraw the team's grants while retaining personal ownership

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--generation\fP=0
	expected current team generation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for unshare

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team-machine(1)\fP
