.nh
.TH "PB-TEAM-LEAVE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-leave - Leave a team


.SH SYNOPSIS
\fBpb team leave <team> [flags]\fP


.SH DESCRIPTION
Leave a team

.PP
Leave your current membership in one team at the expected generation. Access supplied by that membership is withdrawn; owned resources require separate handling.

.PP
Teams use explicit membership and resource grants. Membership alone does not grant device use, ENV values, previews, or tunnels. Mutations use the current team generation to reject stale edits; read pb team get before retrying a conflicting change.

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--generation\fP=0
	expected current team generation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for leave

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team(1)\fP
