.nh
.TH "PB-TEAM-CREATE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-create - Create a team


.SH SYNOPSIS
\fBpb team create <team> [flags]\fP


.SH DESCRIPTION
Create a team

.PP
Create a named team with this account as its initial owner. Membership and resource grants are managed separately after creation.

.PP
Teams use explicit membership and resource grants. Membership alone does not grant device use, ENV values, previews, or tunnels. Mutations use the current team generation to reject stale edits; read pb team get before retrying a conflicting change.

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team(1)\fP
