.nh
.TH "PB-ACCESS" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-access - Open authenticated private access


.SH SYNOPSIS
\fBpb access [flags]\fP


.SH DESCRIPTION
Open authenticated private access

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for access


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-access-device(1)\fP, \fBpb-access-tunnel(1)\fP
