.nh
.TH "PB-BUGREPORT" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-bugreport - Create a redacted Paperboat diagnostic bundle


.SH SYNOPSIS
\fBpb bugreport [flags]\fP


.SH DESCRIPTION
Create a redacted Paperboat diagnostic bundle

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bugreport

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--record\fP[=false]
	record reproduction start and end markers

.PP
\fB--upload\fP[=false]
	upload the exact redacted bundle


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP
