.nh
.TH "PB-CONFIG-UNASSIGN" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-unassign - Remove a config repository assignment


.SH SYNOPSIS
\fBpb config unassign  [flags]\fP


.SH DESCRIPTION
Remove a config repository assignment

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for unassign

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--yes\fP[=false]
	confirm removal


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
