.nh
.TH "PB-CONFIG-TEAM-DEFAULT-UNADOPT" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config-team-default-unadopt - Stop inheriting a team configuration default


.SH SYNOPSIS
\fBpb config team-default-unadopt [flags]\fP


.SH DESCRIPTION
Stop inheriting a team configuration default

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for team-default-unadopt

.PP
\fB--json\fP[=false]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-config(1)\fP
