.nh
.TH "PB-COMPLETION-FISH" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBpb completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.EX
pb completion fish | source
.EE

.PP
To load completions for every new session, execute once:

.EX
pb completion fish > ~/.config/fish/completions/pb.fish
.EE

.PP
You will need to start a new shell for this setup to take effect.

.PP
This command does not support --json output; it rejects that mode before execution. Use --help --json for structured command help.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-completion(1)\fP
