.nh
.TH "PB-CONFIG" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-config - Inspect the local CLI config


.SH SYNOPSIS
\fBpb config [flags]\fP


.SH DESCRIPTION
Inspect the local CLI config

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-config-approve(1)\fP, \fBpb-config-assign(1)\fP, \fBpb-config-conflict(1)\fP, \fBpb-config-customize(1)\fP, \fBpb-config-force(1)\fP, \fBpb-config-path(1)\fP, \fBpb-config-set(1)\fP, \fBpb-config-show(1)\fP, \fBpb-config-status(1)\fP, \fBpb-config-status-bar(1)\fP, \fBpb-config-team-default-adopt(1)\fP, \fBpb-config-team-default-set(1)\fP, \fBpb-config-team-default-unadopt(1)\fP, \fBpb-config-unassign(1)\fP, \fBpb-config-unset(1)\fP
