.nh
.TH "PB-DAEMON-DEVICE-GUARD-UNINSTALL" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-daemon-device-guard-uninstall - Remove device access while retaining cached-address protection


.SH SYNOPSIS
\fBpb daemon device-guard uninstall [flags]\fP


.SH DESCRIPTION
Remove device access while retaining cached-address protection

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	configuration file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	Paperboat server URL


.SH SEE ALSO
\fBpb-daemon-device-guard(1)\fP
