.nh
.TH "PB-DAEMON-SERVICE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-daemon-service - Manage the Paperboat background daemon service


.SH SYNOPSIS
\fBpb daemon service [flags]\fP


.SH DESCRIPTION
Manage the Paperboat background daemon service

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for service


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	configuration file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	Paperboat server URL


.SH SEE ALSO
\fBpb-daemon(1)\fP, \fBpb-daemon-service-install(1)\fP, \fBpb-daemon-service-restart(1)\fP, \fBpb-daemon-service-start(1)\fP, \fBpb-daemon-service-status(1)\fP, \fBpb-daemon-service-stop(1)\fP, \fBpb-daemon-service-uninstall(1)\fP
