.nh
.TH "PB-ENV-VAULT-PASSWORD" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-vault-password - Rewrap unlocked ENV keys with a new password


.SH SYNOPSIS
\fBpb env vault password [flags]\fP


.SH DESCRIPTION
Rewrap unlocked ENV keys with a new password

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for password

.PP
\fB--json\fP[=false]
	print canonical JSON

.PP
\fB--password-file\fP=""
	read the raw master password from an absolute owner-only file

.PP
\fB--password-stdin\fP[=false]
	read the raw master password from non-interactive stdin


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env-vault(1)\fP
