.nh
.TH "PB-ENV-GRANTS" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-grants - Reconcile encrypted ENV team grants


.SH SYNOPSIS
\fBpb env grants [flags]\fP


.SH DESCRIPTION
Reconcile encrypted ENV team grants

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for grants


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env(1)\fP, \fBpb-env-grants-sync(1)\fP
