.nh
.TH "PB-ENV-HOST" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-env-host - Manage encrypted host ENV projections


.SH SYNOPSIS
\fBpb env host [flags]\fP


.SH DESCRIPTION
Manage encrypted host ENV projections

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for host


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-env(1)\fP, \fBpb-env-host-provision(1)\fP
