.nh
.TH "PB-PREVIEW-LIST" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-preview-list - List temporary previews


.SH SYNOPSIS
\fBpb preview list [flags]\fP


.SH DESCRIPTION
List temporary previews

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--json\fP[=false]
	print canonical preview resources as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-preview(1)\fP
