.nh
.TH "PB-PREVIEW-DELETE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-preview-delete - Delete a temporary preview


.SH SYNOPSIS
\fBpb preview delete  [flags]\fP


.SH DESCRIPTION
Delete a temporary preview

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete

.PP
\fB--json\fP[=false]
	print the deleted canonical preview resource as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-preview(1)\fP
