.nh
.TH "PB-PREVIEW-STOP" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-preview-stop - Stop a temporary preview


.SH SYNOPSIS
\fBpb preview stop  [flags]\fP


.SH DESCRIPTION
Stop a temporary preview

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB--json\fP[=false]
	print the stopped canonical preview resource as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-preview(1)\fP
