.nh
.TH "PB-RELAY-LIST" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-relay-list - List relays and measure current latency


.SH SYNOPSIS
\fBpb relay list [flags]\fP


.SH DESCRIPTION
List relays and measure current latency

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-relay(1)\fP
