.nh
.TH "PB-SERVICE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-service - Manage the Paperboat background daemon service


.SH SYNOPSIS
\fBpb service [flags]\fP


.SH DESCRIPTION
Manage the Paperboat background daemon service

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for service


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-service-install(1)\fP, \fBpb-service-restart(1)\fP, \fBpb-service-start(1)\fP, \fBpb-service-status(1)\fP, \fBpb-service-stop(1)\fP, \fBpb-service-uninstall(1)\fP
