.nh
.TH "PB-SESSION-SHARED" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-session-shared - List owned and explicitly shared terminal sessions


.SH SYNOPSIS
\fBpb session shared [flags]\fP


.SH DESCRIPTION
List owned and explicitly shared terminal sessions

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for shared

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-session(1)\fP
