.nh
.TH "PB-TRANSFER-DESTINATION-CLEAR" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-transfer-destination-clear - Clear the default transfer destination


.SH SYNOPSIS
\fBpb transfer destination clear [flags]\fP


.SH DESCRIPTION
Clear the default transfer destination

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for clear

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override

.PP
\fB--session\fP=""
	terminal session ID for a session-specific destination


.SH SEE ALSO
\fBpb-transfer-destination(1)\fP
