.nh
.TH "PB-TEAM-ACCEPT" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-accept - Accept an invitation bound to this account


.SH SYNOPSIS
\fBpb team accept  [flags]\fP


.SH DESCRIPTION
Accept an invitation bound to this account

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for accept

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team(1)\fP
