.nh
.TH "PB-TUNNEL-CONNECTOR-ADD" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-tunnel-connector-add - Add a connector on this host


.SH SYNOPSIS
\fBpb tunnel connector add  [flags]\fP


.SH DESCRIPTION
Add a connector on this host

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--ephemeral\fP[=false]
	use the temporary preview lifecycle

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-tunnel-connector(1)\fP
