.nh
.TH "PB-TEAM-MACHINE-REMOVE" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-machine-remove - Revoke a team-owned machine without personal takeover


.SH SYNOPSIS
\fBpb team machine remove   [flags]\fP


.SH DESCRIPTION
Revoke a team-owned machine without personal takeover

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--confirm\fP=""
	exact machine identifier acknowledging the ownership or revocation effect

.PP
\fB--generation\fP=0
	expected current team generation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team-machine(1)\fP
