.nh
.TH "PB-TRANSFER" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-transfer - Manage file transfers


.SH SYNOPSIS
\fBpb transfer [flags]\fP


.SH DESCRIPTION
Manage file transfers

.PP
With --json, this command group lists its available commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for transfer


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--json\fP[=false]
	print machine-readable JSON

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP, \fBpb-transfer-cancel(1)\fP, \fBpb-transfer-destination(1)\fP, \fBpb-transfer-list(1)\fP, \fBpb-transfer-status(1)\fP
