.nh
.TH "PB-TEAM-TRANSFER" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-team-transfer - Transfer team membership


.SH SYNOPSIS
\fBpb team transfer   [flags]\fP


.SH DESCRIPTION
Transfer team membership

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--generation\fP=0
	expected current team generation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for transfer

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-team(1)\fP
