.nh
.TH "PB-TUNNEL-SHOW" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-tunnel-show - Show a durable tunnel


.SH SYNOPSIS
\fBpb tunnel show  [flags]\fP


.SH DESCRIPTION
Show a durable tunnel

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for show

.PP
\fB--json\fP[=false]
	print canonical JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--ephemeral\fP[=false]
	use the temporary preview lifecycle

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-tunnel(1)\fP
