.nh
.TH "PB-UPDATE-CHECK" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-update-check - Check the signed Paperboat release without installing it


.SH SYNOPSIS
\fBpb update check [flags]\fP


.SH DESCRIPTION
Check the signed Paperboat release without installing it

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for check

.PP
\fB--json\fP[=false]
	print JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb-update(1)\fP
