.nh
.TH "PB-UNINSTALL" "1" "Sep 2026" "Paperboat" "Paperboat CLI"

.SH NAME
pb-uninstall - Completely remove Paperboat from this machine


.SH SYNOPSIS
\fBpb uninstall [flags]\fP


.SH DESCRIPTION
Completely remove Paperboat from this machine

.PP
JSON output is supported with --json.


.SH OPTIONS
\fB--confirmation\fP=""
	exact confirmation phrase: UNINSTALL PAPERBOAT

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall

.PP
\fB--hostname\fP=""
	exact current hostname confirmation

.PP
\fB--json\fP[=false]
	print JSON

.PP
\fB--state-root\fP=""
	additional Paperboat runtime state directory to remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	path to the CLI config file

.PP
\fB--no-customization\fP[=false]
	ignore local shortcuts, command defaults, and TUI preferences

.PP
\fB--server\fP=""
	paperboat-server base URL override


.SH SEE ALSO
\fBpb(1)\fP
