package main

import (
	"strings"

	"github.com/spf13/cobra"
)

// Keep the command reference attached to the command tree: Cobra uses the
// same descriptions for --help, Markdown, and man pages.
func enrichCommandHelp(root *cobra.Command) {
	var visit func(*cobra.Command)
	visit = func(command *cobra.Command) {
		path := command.CommandPath()
		if detail, ok := commandHelpDetails[path]; ok && len(strings.Fields(command.Long)) < 70 {
			long := command.Long
			if long == "" {
				long = command.Short
			}
			if long != "" {
				long += "\n\n"
			}
			long += detail
			if context := commandHelpContext(path); context != "" {
				long += "\n\n" + context
			}
			command.Long = long
		}
		for _, child := range command.Commands() {
			visit(child)
		}
	}
	visit(root)
}

func commandHelpContext(path string) string {
	longest := ""
	for prefix := range commandHelpTopics {
		if path != prefix && strings.HasPrefix(path, prefix+" ") && len(prefix) > len(longest) {
			longest = prefix
		}
	}
	return commandHelpTopics[longest]
}

var commandHelpTopics = map[string]string{
	"pb access":               "Private access requires authorization for the exact target. The listener stays on the local loopback interface, and closing this command closes the forwarding session. Public tunnel publication is managed separately with pb tunnel.",
	"pb auth":                 "Sign-in credentials are stored in the selected local profile for its configured Paperboat server. Account commands use that profile; a missing or rejected session must be repaired with pb auth login before protected resources can be used.",
	"pb config":               "Configuration commands distinguish local CLI settings from synchronized repository content. Inspect current state before changing it; synchronization reports conflicts instead of silently overwriting one side. The --json option provides structured output for scripts where supported.",
	"pb config conflict":      "Conflicts identify exact paths whose local and repository versions cannot be merged automatically. Review the affected path before choosing a side; resolution records a deliberate decision for the next synchronization step.",
	"pb config customize":     "Customization is local to this CLI installation. It can change shortcuts, command defaults, and terminal appearance without changing account credentials or remote resources. Validate or explain preferences before applying an unfamiliar document.",
	"pb config status-bar":    "The status bar is rendered by the interactive terminal client. Preferences affect local presentation and do not change remote sessions. Use preview to inspect the result before relying on a theme or width setting.",
	"pb daemon":               "The daemon owns this machine's background connectivity and local API. Normal lifecycle management uses pb service; daemon run is the foreground entrypoint used by service supervision. Its machine guard subcommands manage protected local machine-name access.",
	"pb daemon machine-guard": "The machine guard is a privileged local helper for protected loopback listeners and trusted local HTTPS. Installation handles certificate trust; public DNS supplies the browser names. Use the dedicated service commands for the ordinary Paperboat daemon.",
	"pb machine":              "Machines are account enrollments with independent names, capabilities, and revocation state. Changes target the selected machine, while pb setup configures the current machine. Revocation disconnects an enrollment rather than just hiding it from the list.",
	"pb env":                  "ENV values are encrypted before they leave the client. Commands select personal, team, or host scope explicitly; list output shows metadata rather than secret values. Unlock the local vault when a key operation requires it.",
	"pb env grants":           "Team ENV grants are reconciled into this account's encrypted vault. Synchronization accepts pending grants; it does not print secret values or grant access merely because an account belongs to a team.",
	"pb env host":             "Host ENV projections contain an explicit selection of encrypted values for an enrolled machine. Provisioning changes the host selection; it does not expose values in command output or implicitly grant access to every scope.",
	"pb env team":             "Team ENV scopes have their own encrypted keys and explicit account grants. Rotation preserves values while replacing access keys; reset discards values. Review the confirmation and affected members before changing custody.",
	"pb env vault":            "The local vault protects ENV key custody with a password and optional recovery code. Locking clears unlocked keys from this machine; removing local custody differs from resetting and deleting account values. Never place a password or recovery code in shell arguments.",
	"pb inbox":                "The Paperboat Inbox receives verified files and exact team requests. Files remain until removed by the user. The receiving path is a local machine setting; team request acceptance is an account policy. A sender manages outgoing batches with pb send.",
	"pb preview":              "A preview exposes a local target through a temporary Paperboat URL or private/team access policy. Inspect its status before sharing the URL, and stop or delete it when no longer needed. Browser HTTP terminates TLS at the edge.",
	"pb send":                 "Send publishes a batch to a machine's Paperboat Inbox. Completion means the receiver verified and recorded the files; status and cancel act on a transfer ID. A default destination can be set separately, while --to chooses one for the current send.",
	"pb service":              "Service commands manage the current user's background Paperboat daemon through the host operating system. The service runs pb daemon; it is not a separate Paperboat binary. Use status to inspect the supervised process and restart after a local configuration change.",
	"pb session":              "Terminal sessions persist independently of a single connection and can be reattached after a disconnect. Sharing grants explicit access to a named session. Closing, deleting, and removing a participant have different effects; inspect the selected session before acting.",
	"pb ssh":                  "Managed SSH resolves the Paperboat machine and then runs OpenSSH with the selected target. Host identity checks remain in force. Standard SSH, SCP, SFTP, and rsync behavior is preserved while Paperboat supplies machine resolution and authorized connectivity.",
	"pb team":                 "Teams use explicit membership and resource grants. Membership alone does not grant machine use, ENV values, previews, or tunnels. Mutations use the current team generation to reject stale edits; read pb team get before retrying a conflicting change.",
	"pb team machine":         "A personal machine can be shared with a team while ownership stays personal, or explicitly transferred to team ownership. Sharing and capability grants are separate decisions. Removing a team-owned machine revokes its enrollment; unsharing a personal machine withdraws that team's access.",
	"pb tunnel":               "Durable tunnels retain identity, routes, connectors, and domains across client sessions. Ephemeral tunnels have a separate lifecycle. Route publication and browser HTTP access require exact authorization; TLS for browser HTTP terminates at the edge.",
	"pb tunnel connector":     "Connectors attach an enrolled host to a durable tunnel. Drain stops new work while allowing existing work to wind down; revoke removes connector authority. Inspect connector state before replacing or removing one.",
	"pb tunnel credentials":   "Connector credentials authorize a tunnel attachment. Rotation replaces that authority and may interrupt existing connectors; use the status and connector commands to confirm recovery.",
	"pb tunnel domain":        "Custom domains require DNS ownership verification before they can serve a route. Domain changes are scoped to one tunnel, and verification status is separate from route readiness. The instructions command returns the required authoritative DNS records.",
	"pb tunnel policy":        "An on-demand policy authorizes an exact machine port for private or team access. A policy does not publish a public URL or grant every port on the machine. Revocation fences subsequent activation.",
	"pb tunnel route":         "Routes map a public or private match to a specific origin and protocol. TLS and host-header options affect the trust boundary and should match the origin. Adding or updating a route may return an operation whose readiness must be checked separately.",
	"pb update":               "Updates use signed release metadata and preserve artifact authenticity and rollback protection. Check inspects an available release; status reports the installed updater state. A failed update should leave the known installation usable and report a recovery action.",
}

var commandHelpDetails = map[string]string{
	"pb config repository":                    "Connect a Git repository to your account, inspect registered repositories, and configure authentication separately on this machine. Connecting a repository does not select local files; define explicit machine path rules before enabling synchronization.",
	"pb config repository connect":            "Register an HTTPS, HTTP, SSH URL or absolute local Git path without embedded credentials. Use --name and --branch to select its display name and branch. Machine authentication and explicit file mappings are configured separately.",
	"pb config repository list":               "List the connected repositories available to your signed-in account, including their stable IDs, display names, and providers. Use the stable repository ID when names are ambiguous or when scripting later configuration commands.",
	"pb config repository credentials":        "Set or remove a private authentication profile for a custom Git repository on this machine. Profiles remain local to the machine and are configured independently from repository registration and the paths selected for synchronization.",
	"pb config repository credentials set":    "Resolve a custom Git repository by ID or name and read its authentication profile from --file. Use --file - for stdin. The profile is validated and stored privately on this machine for repository access.",
	"pb config repository credentials remove": "Resolve a custom Git repository by ID or name and remove this machine's saved authentication profile. The repository registration and its content remain available; configure another profile before operations that require private repository authentication.",
	"pb config sync":                          "Inspect, initialize, validate, or apply this machine's authoritative configuration file. The file defines repository choices and explicit path rules. Validate the effective configuration before applying a confirmed change to the enrolled machine's synchronization assignment.",
	"pb config sync path":                     "Print the authoritative local machine configuration path so you can edit or inspect the source file. This command only resolves the location; it does not create a file or change the machine's synchronization assignment.",
	"pb config sync init":                     "Create a protected empty machine configuration at its authoritative local path. An existing file is preserved and reported as an error. Edit the created file to define repository choices and explicit synchronization path rules.",
	"pb config sync validate":                 "Read this machine's configuration, resolve its repositories and explicit mapped paths, and preview the safe effective synchronization projection. Use --repository for initial repository selection. Validation does not apply a new machine assignment or start synchronization.",
	"pb config sync apply":                    "Read and resolve the machine configuration, preview its effective assignment, then apply the confirmed revision. Use --confirm with the displayed code in noninteractive use. Synced files are plaintext in Git, and prior content remains in repository history.",
	"pb access":                               "Choose machine access for an enrolled machine service or tunnel access for an existing private tunnel route. Each child command opens a local listener and keeps the forwarding process alive until it exits.",
	"pb access machine":                       "--port identifies the exact service on the authorized machine, and --listen chooses the local loopback address. Closing the command closes the forwarding session without publishing a public URL.",
	"pb access tunnel":                        "Resolve a tunnel or route by its exact identity and forward a loopback listener to that authorized private TCP target. --listen selects the local address; the listener is closed when the command ends.",
	"pb approve":                              "Approve an exact peer machine ID for local access, or use --revoke to withdraw that approval. This changes the local daemon's machine trust decision; inspect the ID before approving an unfamiliar peer.",
	"pb auth":                                 "Use login for browser approval on any device, switch for Personal/team workspace selection, status to inspect the active profile, and logout to revoke it. Installation tokens remain part of machine setup, not interactive login.",
	"pb auth login":                           "Print an approval link and open it when a browser is available. Sign in through WorkOS on this or another device and explicitly approve the requesting CLI. No local callback listener or copied token is needed. Interrupted attempts resume securely; the existing account remains active until replacement succeeds.",
	"pb login":                                "Alias for pb auth login. Print an approval link and sign in through WorkOS on any device, including when this machine has no browser. Credentials stay on the requesting CLI and installation or machine ownership is unchanged.",
	"pb auth switch":                          "Alias for pb switch. Select Personal or an available team for resource discovery and new operations. The selection is scoped to the signed-in account and server; running terminals, previews and tunnels keep their existing ownership.",
	"pb auth logout":                          "Revoke the current client session at the server and remove its local credential. If server cancellation cannot complete, the command reports the pending state so revocation can be retried.",
	"pb auth status":                          "Report the active account and session for the configured server. Use this before an account-scoped operation to check which identity the CLI will use.",
	"pb bugreport":                            "Collect a bounded, redacted diagnostic bundle for support. --record controls capture and --upload sends the prepared report; review the output path and support reference before sharing it.",
	"pb completion":                           "Choose bash, fish, powershell, or zsh to print that shell's completion script to standard output. Follow the selected subcommand's installation instructions; generating a script does not modify your shell configuration.",
	"pb config":                               "Show local configuration and synchronization commands. Use show for effective values, path for the active file, and status for repository synchronization. Interactive terminals open local config controls.",
	"pb config approve":                       "Approve the pull revision currently under review for the selected environment. This applies the reviewed revision; it does not approve an unrelated later repository change.",
	"pb config conflict":                      "List current path conflicts, inspect their metadata with show, and read both versions with compare through an encrypted peer connection. Resolve the exact current path by choosing the machine or repository version.",
	"pb config conflict compare":              "Read both current versions of one exact conflict from the target machine through its encrypted peer connection. Content streams in bounded chunks and complete hashes are verified before display. Changed conflict or repository revisions require refreshed status. JSON output returns each verified side as base64 content; this command applies no resolution.",
	"pb config conflict list":                 "List unresolved paths for one environment or across assigned environments. Each entry identifies the path that needs review before synchronization can continue.",
	"pb config conflict resolve":              "Resolve one exact path with --keep to select the machine or repository version. Use compare first to inspect both sides; the chosen direction is recorded for the next synchronization step.",
	"pb config conflict show":                 "Display the path, reason and current status for one environment conflict. Use compare to read the actual machine and repository content before choosing which version to keep with resolve.",
	"pb config customize explain":             "Expand the supplied command arguments using the current local shortcuts and defaults without running the result. Place arguments after -- so they are interpreted as the proposed command.",
	"pb config customize import":              "Validate the JSON preferences document, then replace local customization with its contents. A failed validation leaves the current preferences in place.",
	"pb config customize path":                "Print the location of the local customization document. Use this path when editing or backing up preferences outside the CLI.",
	"pb config customize reset":               "Remove local shortcuts, command defaults, and appearance choices. This preserves sign-in credentials, configured server, and remote resource state; the confirmation code confirms the reset.",
	"pb config customize show":                "Show the effective local preference document, including current shortcuts and appearance settings. The command does not execute any customized command.",
	"pb config customize validate":            "Check the current preference document for invalid keys, values, and command expansions. Validation does not execute a shortcut or change preferences.",
	"pb config force":                         "Force one pull or push direction for the named environment, optionally limited to a path. This bypasses the normal conflict choice for that scope; the confirmation code confirms the direction.",
	"pb config path":                          "Print the active CLI configuration file path. The result identifies local settings, not a synchronized repository or ENV vault file.",
	"pb config set":                           "Write one supported local configuration key. The change affects this CLI installation; inspect pb config show afterward to confirm the effective value.",
	"pb config show":                          "Show effective local configuration after defaults and file settings are applied. Credentials and ENV secret values are not included in this output.",
	"pb config status":                        "Report synchronization state and any pending review or conflict for one environment or all assignments. Use this before approving or forcing a direction.",
	"pb config status-bar":                    "Inspect, set, preview, or reset local status-bar preferences. These settings affect interactive terminal display and do not modify remote shell state.",
	"pb config status-bar preview":            "Render the current status bar at the requested width without opening a remote session. Use it to check truncation and theme choices before connecting.",
	"pb config status-bar reset":              "Restore the built-in status-bar preferences. This only changes local presentation and leaves account, terminal sessions, and remote configuration intact.",
	"pb config status-bar set":                "Set one status-bar preference by key and value. Preview the result before using it in a full-screen terminal application.",
	"pb config status-bar show":               "Show the effective status-bar settings, including defaults and local overrides. This is read-only and does not attach to a session.",
	"pb config team-default-adopt":            "Adopt the selected team's default pull repository for this account using its provider access. Adoption is explicit; personal machine assignments still take precedence.",
	"pb config team-default-set":              "Set a team's default pull repository for members who explicitly adopt it. This changes the team default, not every member's current local assignment.",
	"pb config team-default-unadopt":          "Stop this account inheriting its adopted team repository default. Personal machine assignments, the team's default, and other members' choices remain unchanged.",
	"pb config unassign":                      "Remove a repository assignment from the selected environment. The repository and its content remain; the confirmation code confirms the local synchronization change.",
	"pb config unset":                         "Remove the supported local server setting so the built-in or surrounding configuration applies. This does not revoke the current account session.",
	"pb connect":                              "Select an environment by name, create or reattach a durable terminal session, and bridge the local terminal. Use --session for a specific session or new to start another one; connection status is reported separately from readiness.",
	"pb daemon":                               "Run the daemon under supervision or manage the privileged machine guard. Most users should use pb service to install, start, stop, and inspect the background process.",
	"pb daemon machine-guard":                 "Install or uninstall the privileged guard that protects machine-name access. The run entrypoint is invoked by operating-system supervision rather than normal interactive use.",
	"pb daemon machine-guard install":         "Install the root-owned guard service for the fixed protected 127.100.0.0/16 loopback range and configure local HTTPS certificate trust automatically.",
	"pb daemon machine-guard run":             "Start the foreground machine-guard process for its supervisor. This entrypoint is used by the installed root-owned service and normally should not be run from an interactive shell.",
	"pb daemon machine-guard uninstall":       "Remove the privileged machine-access integration while retaining cached-address protection. This does not uninstall the ordinary current-user Paperboat daemon service.",
	"pb daemon run":                           "Run the endpoint daemon in the foreground for service supervision. It remains active until stopped and uses the selected local configuration and server; use pb service for ordinary lifecycle control.",
	"pb machine":                              "List account machines, print a one-shot enrollment command, and manage one machine's name, availability, capabilities, or revocation. All mutations are scoped to an exact enrollment; a machine's online state does not by itself grant a service capability.",
	"pb machine add":                          "Create an enrollment command for Linux, macOS, or Windows and optionally give the new machine a name. The printed one-shot material should be used on the intended machine.",
	"pb machine availability":                 "Set whether the selected machine remains available while idle or is allowed to sleep, according to --mode. Keep-awake mode requires a confirmation code because it can affect battery use and heat.",
	"pb machine capabilities":                 "Enable or disable incoming terminal, managed SSH, file receive, and preview tunnel services for one machine. Disabled services are not made available simply because the machine is online.",
	"pb machine list":                         "Show enrolled machines and their current account-visible state. Use the returned machine identity for rename, capabilities, availability, or revoke.",
	"pb machine rename":                       "Change the display name of one enrolled machine. The enrollment identity and grants stay attached to the machine; callers should use the returned name for future selection.",
	"pb machine revoke":                       "Disconnect and revoke the selected enrollment. Existing machine credentials lose authority; the confirmation code confirms this account-level removal.",
	"pb doctor":                               "Check authentication, local runtime, and connectivity for the current setup or one selected machine. --repair performs supported local fixes; without it, the command reports findings and recovery guidance.",
	"pb edge":                                 "List account-visible tunnel edges and their observed state. The list includes hosted and selected self-hosted nodes according to the tunnel pool, with an explicit display-only hosted fallback when no self-hosted node is selected.",
	"pb env":                                  "Manage encrypted ENV values by personal, team, or host scope. Vault commands control key custody, while set and unset change exact values. Listing shows metadata without revealing a value.",
	"pb env grants":                           "Reconcile encrypted grants offered by a team into this account's vault. Use sync after a team has explicitly granted access.",
	"pb env grants sync":                      "Accept pending team grants into the unlocked local vault. Only grants addressed to this account are reconciled; secret values are not printed.",
	"pb env host":                             "Provision an exact selection of encrypted ENV values to an enrolled host. The selection must be explicit and can be emptied deliberately.",
	"pb env host provision":                   "Select values for the named host with --select, or pass --empty to clear its projection. The host receives only the chosen encrypted scope, not every ENV value in the account.",
	"pb env list":                             "List ENV names and scope metadata, optionally limited to a team or host. This does not print plaintext values or key material.",
	"pb env rotate":                           "Rotate personal ENV scope keys while retaining the values. Complete or cancel an interrupted rotation before starting another custody change.",
	"pb env rotate cancel":                    "Cancel an uncommitted personal key rotation using the exact confirmation. A completed rotation cannot be undone by this command.",
	"pb env set":                              "Set one exact ENV name using a hidden interactive prompt, a bounded stdin stream, or --value-file. Use --team or --machine to choose a nonpersonal scope; the value is never part of the command output.",
	"pb env team":                             "Create team ENV scopes, grant access, rotate keys, revoke members, or reset values. These operations affect encrypted team custody rather than ordinary team membership alone.",
	"pb env team create":                      "Create an encrypted scope for the selected team. Values added later remain separate from personal ENV values and require explicit member grants.",
	"pb env team grant":                       "Give one account access to the selected encrypted team ENV scope. The account must still accept and reconcile its grant before using values.",
	"pb env team reset":                       "Discard every value in the selected team scope and replace its key. Use the exact confirmation only when value loss is intended.",
	"pb env team revoke":                      "Remove selected members and rotate the team scope key so subsequent access is fenced. --total-loss chooses the destructive recovery path when preserving existing values is impossible.",
	"pb env team rotate":                      "Replace the team scope key while preserving its values for remaining authorized members. The command requires an exact confirmation for this custody transition.",
	"pb env unset":                            "Delete one ENV name from the selected personal, team, or host scope. the confirmation code confirms removal; other names and scopes remain intact.",
	"pb env vault":                            "Initialize, unlock, lock, recover, rewrap, or remove local custody of ENV keys. Reset is the destructive account-level path and is separate from locking or removing one machine's custody.",
	"pb env vault init":                       "Create password-protected local key custody for this account. Read the password from a private file or stdin; --recovery-file saves a newly generated recovery code to a new file.",
	"pb env vault lock":                       "Clear unlocked ENV keys from this machine while retaining encrypted custody. Unlock with the password before another key-dependent operation.",
	"pb env vault password":                   "Rewrap unlocked vault keys under a new password without changing ENV values. Supply the new password through stdin or a private file rather than a shell argument.",
	"pb env vault recover":                    "Use the recovery code to regain vault access and replace the password and recovery code. Store the newly generated code in a new owner-only file.",
	"pb env vault recovery":                   "Enable, replace, or disable optional recovery-code custody. Disabling recovery removes that recovery path without deleting ENV values.",
	"pb env vault remove":                     "Remove this machine's local vault custody after exact confirmation. This differs from reset: account ENV values and other authorized machines are not deleted.",
	"pb env vault reset":                      "Replace personal ENV keys and delete every personal value after exact account confirmation. This is destructive and differs from local lock, remove, or password change.",
	"pb env vault resume":                     "Reconcile a vault publication interrupted after a partial remote transition. Run this before retrying another key operation when the vault reports pending state.",
	"pb env vault unlock":                     "Unlock encrypted local custody with the password supplied interactively, by stdin, or from a private file. No ENV value is printed by unlocking.",
	"pb environments":                         "List enrolled machines available to this account as terminal environments. Use the displayed name or ID with pb connect; visibility does not imply a machine is ready.",
	"pb exec":                                 "Run the exact argv after -- on the selected machine, with optional working directory, environment entries, PTY, and timeout. Output and exit status come from the remote command; use --json for structured events.",
	"pb inbox":                                "Inspect or set the local receiving directory, the account's team request acceptance policy, and pending team file requests. Approve or decline an exact request by ID; outgoing transfers are sent and managed under pb send.",
	"pb inbox approve":                        "Approve one exact pending team file request at its expected generation. The approved sender can deliver only the requested batch; review request details before accepting.",
	"pb inbox decline":                        "Reject one exact pending team file request at its expected generation. The sender receives a decline rather than an implicit timeout.",
	"pb inbox path":                           "Print the current local Inbox directory used for received files. This is a receiver setting; it does not choose a destination for outgoing sends.",
	"pb inbox policy":                         "Show or set manual versus automatic acceptance for team file requests. --receipt-email controls receipt notification behavior, not file retention.",
	"pb inbox requests":                       "List pending team file requests and their identities for review. Use approve or decline with the exact request ID and current generation.",
	"pb inbox reset":                          "Restore the default local receiving directory for future files. The account's team request acceptance policy and already delivered files are unchanged.",
	"pb inbox set":                            "Set an explicit local directory for future received files. The command configures the receiving side; it does not move already delivered files.",
	"pb install":                              "Install this executable and its local background service on the current machine. --install-dir selects the binary location; use pb service status after installation to inspect the supervised daemon.",
	"pb logout":                               "Revoke and remove the current CLI client session. This top-level command has the same account effect as pb auth logout and reports any pending server revocation.",
	"pb pair":                                 "Enroll this machine with a one-shot token, optionally reading it from a private file. Name, shell, and state-root options target the local installation; enrollment binds a new machine identity to the account.",
	"pb ping":                                 "Send authenticated health exchanges to one enrolled machine. --count and --timeout bound the measurements; a reachable transport alone is not a claim that the target service is ready.",
	"pb preview":                              "Start a temporary preview for a local port, URL, or path. --private or --team controls who may open it; public browser HTTP ends TLS at the edge. Use status and stop to manage its lifecycle.",
	"pb preview delete":                       "End the selected temporary preview and its published access. This command currently performs the same stop operation as pb preview stop; use status first if you need its current state.",
	"pb preview inspect":                      "Read or manage bounded HTTP captures retained by the local daemon for one preview. --body and --raw expose capture content, while enable, disable, and purge change capture state; treat output as potentially sensitive.",
	"pb preview list":                         "List account-visible temporary previews and their state. Select an exact preview identity for status, inspect, replay, stop, or delete.",
	"pb preview replay":                       "Replay one retained HTTP request to the same preview origin by capture ID. This deliberately repeats an HTTP action; use an idempotency key when the origin supports one.",
	"pb preview status":                       "Show the selected preview's current publication and connector state. A URL existing in the account is distinct from a ready, reachable origin.",
	"pb preview stop":                         "Stop the selected temporary preview's active forwarding. Other previews and durable tunnels remain separate resources.",
	"pb relay":                                "Inspect relay regions and self-hosted relay installations selected by the account's relay pool. The list measures hosted network latency and labels self-hosted readiness separately.",
	"pb reset":                                "Remove the current local Paperboat setup before fresh enrollment. Exact confirmation and host identity guard against resetting the wrong machine; use uninstall for a complete local removal.",
	"pb resolve":                              "Ask the local daemon to resolve a peer machine query into authorized address, forwarding, and tag information. This reports locally known peer state; it does not approve a new machine.",
	"pb rsync":                                "Run standard rsync arguments with Paperboat machine-name resolution and authorized connectivity. File selection, deletion flags, and exit behavior remain rsync's responsibility; inspect its command line before synchronizing.",
	"pb scp":                                  "Run standard scp with Paperboat machine-name resolution and authorized connectivity. Source and destination syntax remains OpenSSH-compatible; host identity checks still apply.",
	"pb send":                                 "Send one or more paths to the selected machine's Inbox. The command succeeds only after receiver verification and a durable receipt; --session associates the transfer with a terminal session.",
	"pb send cancel":                          "Cancel an outgoing transfer by its exact transfer ID, optionally selecting a machine with --on. Cancellation reports the resulting batch state; already delivered files are not silently deleted.",
	"pb send destination":                     "Show the saved default machine for outgoing sends. This setting does not affect the Inbox receiving directory and can be overridden for one send with --to.",
	"pb send destination clear":               "Remove the saved default recipient for future sends. Existing transfers and received files are unaffected; a later send must specify --to or set another default.",
	"pb send destination set":                 "Save one enrolled machine as the default recipient for future sends. A command's explicit --to selection takes precedence over this local default.",
	"pb send list":                            "List outgoing transfer batches, optionally limited by machine, terminal session, or result count. Use a returned transfer ID with status or cancel.",
	"pb send status":                          "Inspect one outgoing batch's delivery progress and receipt by transfer ID. --on selects the machine when needed; successful publication is distinct from final receiver verification.",
	"pb service":                              "Install, start, stop, restart, inspect, or uninstall the current-user daemon service. The service supervises pb daemon and is separate from the privileged machine guard.",
	"pb service install":                      "Register the current executable as the current user's Paperboat daemon service, using the selected server and configuration. Installation does not enroll a new account by itself.",
	"pb service restart":                      "Restart the supervised current-user daemon after a local configuration or binary change. Active connections may be interrupted; inspect pb service status afterward.",
	"pb service start":                        "Start the installed current-user daemon service. A successful supervisor action should be followed by status or doctor when endpoint readiness matters.",
	"pb service status":                       "Report whether the current-user daemon service is installed and running. Runtime readiness and account connectivity may require pb status or pb doctor as well.",
	"pb service stop":                         "Stop the supervised current-user daemon. Local forwarding and incoming connectivity owned by that process stop until it is started again.",
	"pb service uninstall":                    "Remove the current-user daemon service registration. This does not by itself revoke the account's machine enrollment or uninstall the privileged machine guard.",
	"pb session":                              "List, attach, rename, close, or delete durable terminal sessions, and manage exact session sharing. Use --all only on commands that expose it and inspect the affected environment first.",
	"pb session attach":                       "Choose a durable session for an environment and attach the local terminal. If several sessions exist, select the exact one; status-bar options affect only this terminal presentation.",
	"pb session close":                        "Close one selected terminal session or every applicable session with --all. Closing ends the remote process and deletes its recent output; the closed record remains temporarily. With --all, run the command once to receive a short-lived confirmation token, then run the displayed command to proceed. The same code flow applies to one session.",
	"pb session delete":                       "Delete a closed non-default terminal session record, or use --all for all such records in the environment. Close a running terminal first. With --all, run the command once to receive a short-lived confirmation token, then run the displayed command to proceed. the confirmation code confirms only single-session deletion.",
	"pb session join":                         "Join an explicitly shared terminal by session ID. Your viewer or interactive role comes from the owner's grant; joining does not create a new ownership session.",
	"pb session list":                         "List durable sessions with automatic application title or foreground process and current directory where observed. “Started in” labels the launch directory when current metadata is unavailable. --wide adds the session ID; choose an exact session ID for attach, rename, close, or sharing.",
	"pb session participants":                 "Show current participants and sharing grants for one session. Use this to review access before removing a teammate or ending sharing.",
	"pb session remove":                       "Remove one teammate from a session, including access that came through an all-team grant. The owner's session remains active for other authorized participants.",
	"pb session rename":                       "Change the display name of one durable session. This is an identity label, not a bulk rename; the default session cannot be renamed.",
	"pb session share":                        "Grant a named teammate or team viewer or interactive access to one exact session. --all selects the all-team audience; --role controls whether the recipient can type.",
	"pb session shared":                       "List sessions you own and sessions explicitly shared with you. This inventory shows access, not a blanket right to all sessions in a team environment.",
	"pb session unshare":                      "End sharing for one session while preserving the owner's terminal and history. Existing participants lose the shared grant according to the resulting authorization state.",
	"pb setup":                                "Enroll and configure this machine, create its Inbox, and install the running executable as the Paperboat service. Capability flags choose incoming services; recovery output must be stored carefully.",
	"pb sftp":                                 "Run standard sftp with Paperboat machine-name resolution and authorized connectivity. Interactive file operations and exit behavior remain OpenSSH-compatible; host identity checks stay enabled.",
	"pb ssh":                                  "Connect to an enrolled machine through OpenSSH using Paperboat resolution. Optional arguments after -- go to OpenSSH; the command preserves SSH host-key verification and reports identity changes for deliberate approval.",
	"pb ssh doctor":                           "Check the selected machine's managed SSH configuration and local integration. It reports actionable findings without approving a changed host identity.",
	"pb ssh trust-host":                       "Approve one pending SSH host-key change by its exact SHA256 fingerprint. Verify the fingerprint out of band before accepting it; this changes trust for the selected machine.",
	"pb status":                               "Show the local endpoint's Paperboat state or the selected machine's observed status. This is a snapshot rather than a readiness wait; use doctor for a deeper check, service status for supervisor state, and pb wait for a named readiness condition.",
	"pb tag":                                  "Assign the supplied tags to an exact machine ID through the local daemon. Tags aid machine discovery and resolution; they do not grant access by themselves.",
	"pb team invitations":                     "Discover every authorized invitation for your account, or list invitations for a team you administer. Inventory pagination is followed to completion. Use the exact invitation identity to inspect, accept a received invitation, or cancel an invitation you administer.",
	"pb team invitation":                      "Read one exact invitation visible to your account or team administration authority. This command displays metadata and does not accept or cancel it. Use the corresponding explicit invitation action after reviewing its team and recipient.",
	"pb team accept":                          "Accept an invitation explicitly addressed to this account. The resulting membership does not automatically grant access to every resource owned or shared by the team.",
	"pb team activity":                        "Read recent owner/admin activity for one team, with cursor and limit for pagination. Entries support review of membership and grant changes within the retention window.",
	"pb team attach":                          "Attach or detach an exact personal preview or tunnel to a team. --generation guards against stale changes, and --active chooses the desired attachment state.",
	"pb team cancel-invite":                   "Cancel one outstanding invitation for the selected team at its expected generation. The invited account cannot accept that invitation afterward.",
	"pb team create":                          "Create a named team with this account as its initial owner. Membership and resource grants are managed separately after creation.",
	"pb team delete":                          "Delete a team after exact confirmation and a matching generation. This affects team ownership and grants; inspect attached resources and enrolled team machines first.",
	"pb team machine":                         "Share personal machines, grant exact capabilities, or transfer ownership to a team. Team membership alone never grants terminal, SSH, or file access to a machine.",
	"pb team machine grant":                   "Set the complete machine capability list for one member or all members at the expected team generation. --active can withdraw a grant; omitted capabilities are not implied.",
	"pb team machine remove":                  "Revoke a team-owned machine enrollment after exact confirmation. Ownership does not return to a former personal enroller; access is withdrawn from team members.",
	"pb team machine share":                   "Share a personal machine with one team while keeping personal ownership. Members need explicit capability grants before they can use it.",
	"pb team machine transfer-to-team":        "Transfer a personal machine enrollment into team ownership after exact confirmation and generation check. This is different from sharing and withdraws unrelated personal team shares.",
	"pb team machine unshare":                 "Withdraw one team's access to a personally owned machine while retaining that enrollment. Other independent personal ownership remains intact.",
	"pb team get":                             "Read one team's current membership, permissions, and generation. Use the returned generation for the next mutation to avoid overwriting a newer change.",
	"pb team grant":                           "Set or revoke an explicit ENV, preview, or tunnel permission for one account and resource. --active selects grant state, and --generation rejects stale team edits.",
	"pb team invite":                          "Invite one exact account to the selected team at its current generation. The recipient must accept; an invitation is not immediate membership or a resource grant.",
	"pb team leave":                           "Leave your current membership in one team at the expected generation. Access supplied by that membership is withdrawn; owned resources require separate handling.",
	"pb team list":                            "List teams visible to the signed-in account and their basic state. Select one with pb team get to inspect its current generation and grants.",
	"pb team remove":                          "Remove one member from a team at the expected generation. Team resource access supplied through membership is withdrawn for that account.",
	"pb team role":                            "Set one member's role to admin or member at the expected generation. This changes team management authority, not the member's explicit resource grants.",
	"pb team transfer":                        "Transfer team ownership to the named account at the expected generation. Review the target account and current team state before changing owner authority.",
	"pb tunnel":                               "Create or manage a durable tunnel, or start an ephemeral tunnel with --ephemeral and a local target. Durable routes, domains, connectors, and traffic state have separate subcommands.",
	"pb tunnel connector":                     "List, add, drain, or revoke host connectors for one durable tunnel. Draining is a graceful transition; revocation withdraws connector authority.",
	"pb tunnel connector add":                 "Add a connector for the selected durable tunnel on this host. Inspect tunnel and connector status before advertising a route through the new attachment.",
	"pb tunnel connector drain":               "Stop assigning new work to one connector and optionally wait for existing work to finish. --timeout bounds the wait; the connector remains distinct from a revoked one.",
	"pb tunnel connector list":                "List connectors attached to one durable tunnel with cursor and limit pagination. Use the returned connector identity for drain or revoke.",
	"pb tunnel connector revoke":              "Withdraw one connector's authority for the selected tunnel. --wait and --timeout control observation of shutdown; the confirmation code confirms revocation.",
	"pb tunnel create":                        "Create a durable tunnel with a local port or origin and optional domain, privacy, and team settings. The returned operation may still be connecting; --wait observes readiness within --timeout.",
	"pb tunnel credentials":                   "Manage credentials that authorize tunnel connectors. Rotate deliberately and inspect connector recovery after the transition.",
	"pb tunnel credentials rotate":            "Rotate the selected tunnel's connector credentials and revoke the old authority. --wait observes the operation; the confirmation code confirms a change that may interrupt connectors.",
	"pb tunnel delete":                        "Delete one durable tunnel's endpoints and routes and revoke its connectors, while preserving user-managed DNS records. the confirmation code confirms removal; inspect the tunnel and domains first.",
	"pb tunnel doctor":                        "Diagnose placement, connector, edge, and origin health for one tunnel. --bundle can prepare bounded supporting diagnostics, and --write-bundle selects a local output file.",
	"pb tunnel domain":                        "Manage custom domains bound to a durable tunnel. Add the hostname, follow authoritative DNS instructions, verify ownership, then inspect route readiness.",
	"pb tunnel domain add":                    "Register a hostname for one tunnel or route. Registration alone does not prove ownership or make traffic ready; use instructions and verify to complete DNS setup.",
	"pb tunnel domain instructions":           "Show the authoritative DNS records required for one tunnel domain. Apply them at the domain's DNS provider before running verify.",
	"pb tunnel domain list":                   "List domains for one durable tunnel with pagination. The returned state distinguishes registration from verified ownership and serving readiness.",
	"pb tunnel domain remove":                 "Remove one domain binding after confirmation. DNS records managed by the user are not silently removed by this command.",
	"pb tunnel domain verify":                 "Check DNS ownership for one registered domain and update its verification state. --wait observes the operation; serving still depends on route and connector readiness.",
	"pb tunnel inspect":                       "Read or manage bounded HTTP captures for a tunnel, optionally filtered by route. --body and --raw expose retained content; enable, disable, and purge change capture state.",
	"pb tunnel list":                          "List durable tunnels visible to this account with cursor and limit pagination. Select an exact tunnel for show, status, routes, domains, or lifecycle commands.",
	"pb tunnel logs":                          "Read recent tunnel events and optionally follow new events at the requested interval. Cursor and limit bound retrieval; logs are diagnostic rather than a substitute for status.",
	"pb tunnel pause":                         "Pause new traffic for one durable tunnel while retaining its identity, routes, domains, and connector configuration. --wait observes the resulting state.",
	"pb tunnel policy":                        "Inspect, allow, or revoke exact on-demand private port policies. A policy authorizes a target port but does not publish it as a public tunnel.",
	"pb tunnel policy allow":                  "Authorize on-demand access to one machine port or URL with an exact access audience and optional expiry. --generation protects updates to an existing policy.",
	"pb tunnel policy get":                    "Show one on-demand port policy, including its target and authorization state. Use its identity and generation for a deliberate revoke.",
	"pb tunnel policy revoke":                 "Revoke one exact on-demand port policy at its expected generation. Subsequent activations are denied; this does not delete unrelated tunnel routes.",
	"pb tunnel replay":                        "Replay one retained HTTP request to the same tunnel origin and route. This can repeat a side effect; use the capture identity and optional idempotency key deliberately.",
	"pb tunnel resume":                        "Resume new traffic for a paused durable tunnel without creating a new identity. --wait observes readiness; connector and origin failures may still need repair.",
	"pb tunnel route":                         "List, add, update, or remove exact routes for a durable tunnel. Each route binds protocol, match, and origin settings under the tunnel's authorization boundary.",
	"pb tunnel route add":                     "Add a route to one durable tunnel, selecting protocol, match, origin, and optional TLS behavior. The operation can remain connecting after the command returns; use --wait or status to confirm readiness.",
	"pb tunnel route list":                    "List routes and their identifiers for one durable tunnel with pagination. Inspect the exact route before updating or removing it.",
	"pb tunnel route remove":                  "Remove one route from a durable tunnel after confirmation. The tunnel and its other routes and connectors remain available.",
	"pb tunnel route update":                  "Change explicit fields of one route, including origin, match, protocol, or TLS options. Clear flags remove individual overrides; check the resulting operation and status before assuming traffic moved.",
	"pb tunnel show":                          "Show one durable tunnel's configured identity, routes, domains, and control state. Use status for current health and logs for event history.",
	"pb tunnel status":                        "Show current health for one durable tunnel. --watch refreshes observations at --interval; a configured route is not necessarily ready to serve traffic.",
	"pb tunnel stop":                          "Stop an ephemeral tunnel or preview by its identity. Durable tunnels have pause, resume, and delete commands with different lifecycle effects.",
	"pb uninstall":                            "Remove Paperboat services, binaries, credentials, configuration, and runtime state after exact host and confirmation checks. The local Inbox and its received files are preserved; inspect retained account resources separately.",
	"pb update":                               "Download and verify a signed Paperboat release, then review and approve its exact candidate before installation. Check and status are read-only; download never restarts services. Ordinary installation reconnects connections while preserving running shells; process-owner updates warn before ending running work. Recovery uses trusted artifacts.",
	"pb update download":                      "Download and verify the signed release without changing running services. Review the candidate and use pb update --approve with its exact ID to install. Ordinary installation reconnects connections while preserving running shells; process-owner updates warn before ending running work.",
	"pb update check":                         "Check trusted signed release metadata for a newer compatible artifact without installing it. The result can report availability and trust errors separately from installed state.",
	"pb update status":                        "Show the installed release and updater state, including any pending or failed transition. This reads local update state rather than downloading and installing a new release.",
	"pb wait":                                 "Wait for the selected machine to satisfy a named readiness condition from --for. --timeout bounds the wait, and an expired wait reports a failure instead of treating mere connectivity as readiness.",
}
