// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CanHostTerminals bool                   `protobuf:"varint,1,opt,name=can_host_terminals,json=canHostTerminals,proto3" json:"can_host_terminals,omitempty"`
	CanMountSsh      bool                   `protobuf:"varint,2,opt,name=can_mount_ssh,json=canMountSsh,proto3" json:"can_mount_ssh,omitempty"`
	CanExportPorts   bool                   `protobuf:"varint,3,opt,name=can_export_ports,json=canExportPorts,proto3" json:"can_export_ports,omitempty"`
	ExportedPorts    []int32                `protobuf:"varint,4,rep,packed,name=exported_ports,json=exportedPorts,proto3" json:"exported_ports,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MachineCapabilities) Reset() {
	*x = MachineCapabilities{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCapabilities) ProtoMessage() {}

func (x *MachineCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCapabilities.ProtoReflect.Descriptor instead.
func (*MachineCapabilities) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *MachineCapabilities) GetCanHostTerminals() bool {
	if x != nil {
		return x.CanHostTerminals
	}
	return false
}

func (x *MachineCapabilities) GetCanMountSsh() bool {
	if x != nil {
		return x.CanMountSsh
	}
	return false
}

func (x *MachineCapabilities) GetCanExportPorts() bool {
	if x != nil {
		return x.CanExportPorts
	}
	return false
}

func (x *MachineCapabilities) GetExportedPorts() []int32 {
	if x != nil {
		return x.ExportedPorts
	}
	return nil
}

type MachinePosture struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Os                    string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion             string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Hostname              string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	RequestedCapabilities *MachineCapabilities   `protobuf:"bytes,4,opt,name=requested_capabilities,json=requestedCapabilities,proto3" json:"requested_capabilities,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MachinePosture) Reset() {
	*x = MachinePosture{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachinePosture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinePosture) ProtoMessage() {}

func (x *MachinePosture) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinePosture.ProtoReflect.Descriptor instead.
func (*MachinePosture) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *MachinePosture) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MachinePosture) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *MachinePosture) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachinePosture) GetRequestedCapabilities() *MachineCapabilities {
	if x != nil {
		return x.RequestedCapabilities
	}
	return nil
}

type MachinePostureCheck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Allowed             bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RejectionReason     string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	GrantedCapabilities *MachineCapabilities   `protobuf:"bytes,3,opt,name=granted_capabilities,json=grantedCapabilities,proto3" json:"granted_capabilities,omitempty"`
	RequiresApproval    bool                   `protobuf:"varint,4,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	Approved            bool                   `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MachinePostureCheck) Reset() {
	*x = MachinePostureCheck{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachinePostureCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachinePostureCheck) ProtoMessage() {}

func (x *MachinePostureCheck) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachinePostureCheck.ProtoReflect.Descriptor instead.
func (*MachinePostureCheck) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *MachinePostureCheck) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *MachinePostureCheck) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *MachinePostureCheck) GetGrantedCapabilities() *MachineCapabilities {
	if x != nil {
		return x.GrantedCapabilities
	}
	return nil
}

func (x *MachinePostureCheck) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *MachinePostureCheck) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Posture       *MachinePosture        `protobuf:"bytes,4,opt,name=posture,proto3" json:"posture,omitempty"`
	Endpoints     []string               `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SyncRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *SyncRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SyncRequest) GetPosture() *MachinePosture {
	if x != nil {
		return x.Posture
	}
	return nil
}

func (x *SyncRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *SyncRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	AssignedIp    string                 `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	Endpoints     []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Capabilities  *MachineCapabilities   `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	Approved      bool                   `protobuf:"varint,8,opt,name=approved,proto3" json:"approved,omitempty"`
	ExportedPorts []int32                `protobuf:"varint,9,rep,packed,name=exported_ports,json=exportedPorts,proto3" json:"exported_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *PeerUpdate) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerUpdate) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PeerUpdate) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *PeerUpdate) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *PeerUpdate) GetCapabilities() *MachineCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerUpdate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerUpdate) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PeerUpdate) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *PeerUpdate) GetExportedPorts() []int32 {
	if x != nil {
		return x.ExportedPorts
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	AssignedIp    string                 `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	PostureCheck  *MachinePostureCheck   `protobuf:"bytes,3,opt,name=posture_check,json=postureCheck,proto3" json:"posture_check,omitempty"`
	Peers         []*PeerUpdate          `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	RevokedPeers  []string               `protobuf:"bytes,5,rep,name=revoked_peers,json=revokedPeers,proto3" json:"revoked_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SyncResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *SyncResponse) GetPostureCheck() *MachinePostureCheck {
	if x != nil {
		return x.PostureCheck
	}
	return nil
}

func (x *SyncResponse) GetPeers() []*PeerUpdate {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SyncResponse) GetRevokedPeers() []string {
	if x != nil {
		return x.RevokedPeers
	}
	return nil
}

type SetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsRequest) Reset() {
	*x = SetTagsRequest{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsRequest) ProtoMessage() {}

func (x *SetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsRequest.ProtoReflect.Descriptor instead.
func (*SetTagsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SetTagsRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SetTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsResponse) Reset() {
	*x = SetTagsResponse{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsResponse) ProtoMessage() {}

func (x *SetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsResponse.ProtoReflect.Descriptor instead.
func (*SetTagsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SetTagsResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SetTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SetTagsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x04sync\"\xb8\x01\n" +
	"\x13MachineCapabilities\x12,\n" +
	"\x12can_host_terminals\x18\x01 \x01(\bR\x10canHostTerminals\x12\"\n" +
	"\rcan_mount_ssh\x18\x02 \x01(\bR\vcanMountSsh\x12(\n" +
	"\x10can_export_ports\x18\x03 \x01(\bR\x0ecanExportPorts\x12%\n" +
	"\x0eexported_ports\x18\x04 \x03(\x05R\rexportedPorts\"\xad\x01\n" +
	"\x0eMachinePosture\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12P\n" +
	"\x16requested_capabilities\x18\x04 \x01(\v2\x19.sync.MachineCapabilitiesR\x15requestedCapabilities\"\xf1\x01\n" +
	"\x13MachinePostureCheck\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12L\n" +
	"\x14granted_capabilities\x18\x03 \x01(\v2\x19.sync.MachineCapabilitiesR\x13grantedCapabilities\x12+\n" +
	"\x11requires_approval\x18\x04 \x01(\bR\x10requiresApproval\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\"\xc3\x01\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12.\n" +
	"\aposture\x18\x04 \x01(\v2\x14.sync.MachinePostureR\aposture\x12\x1c\n" +
	"\tendpoints\x18\x05 \x03(\tR\tendpoints\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\xa8\x02\n" +
	"\n" +
	"PeerUpdate\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x12=\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x19.sync.MachineCapabilitiesR\fcapabilities\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\x12\x1a\n" +
	"\bapproved\x18\b \x01(\bR\bapproved\x12%\n" +
	"\x0eexported_ports\x18\t \x03(\x05R\rexportedPorts\"\xd8\x01\n" +
	"\fSyncResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1f\n" +
	"\vassigned_ip\x18\x02 \x01(\tR\n" +
	"assignedIp\x12>\n" +
	"\rposture_check\x18\x03 \x01(\v2\x19.sync.MachinePostureCheckR\fpostureCheck\x12&\n" +
	"\x05peers\x18\x04 \x03(\v2\x10.sync.PeerUpdateR\x05peers\x12#\n" +
	"\rrevoked_peers\x18\x05 \x03(\tR\frevokedPeers\"C\n" +
	"\x0eSetTagsRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"^\n" +
	"\x0fSetTagsResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2x\n" +
	"\vSyncService\x121\n" +
	"\x04Sync\x12\x11.sync.SyncRequest\x1a\x12.sync.SyncResponse(\x010\x01\x126\n" +
	"\aSetTags\x12\x14.sync.SetTagsRequest\x1a\x15.sync.SetTagsResponseBFZDgithub.com/pinksaucepasta/paperboat/internal/controlsync/proto;protob\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sync_proto_goTypes = []any{
	(*MachineCapabilities)(nil), // 0: sync.MachineCapabilities
	(*MachinePosture)(nil),      // 1: sync.MachinePosture
	(*MachinePostureCheck)(nil), // 2: sync.MachinePostureCheck
	(*SyncRequest)(nil),         // 3: sync.SyncRequest
	(*PeerUpdate)(nil),          // 4: sync.PeerUpdate
	(*SyncResponse)(nil),        // 5: sync.SyncResponse
	(*SetTagsRequest)(nil),      // 6: sync.SetTagsRequest
	(*SetTagsResponse)(nil),     // 7: sync.SetTagsResponse
}
var file_sync_proto_depIdxs = []int32{
	0, // 0: sync.MachinePosture.requested_capabilities:type_name -> sync.MachineCapabilities
	0, // 1: sync.MachinePostureCheck.granted_capabilities:type_name -> sync.MachineCapabilities
	1, // 2: sync.SyncRequest.posture:type_name -> sync.MachinePosture
	0, // 3: sync.PeerUpdate.capabilities:type_name -> sync.MachineCapabilities
	2, // 4: sync.SyncResponse.posture_check:type_name -> sync.MachinePostureCheck
	4, // 5: sync.SyncResponse.peers:type_name -> sync.PeerUpdate
	3, // 6: sync.SyncService.Sync:input_type -> sync.SyncRequest
	6, // 7: sync.SyncService.SetTags:input_type -> sync.SetTagsRequest
	5, // 8: sync.SyncService.Sync:output_type -> sync.SyncResponse
	7, // 9: sync.SyncService.SetTags:output_type -> sync.SetTagsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
