// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/daemonrpc/proto/daemon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_StreamStatus_FullMethodName  = "/daemonrpc.DaemonService/StreamStatus"
	DaemonService_ResolveDevice_FullMethodName = "/daemonrpc.DaemonService/ResolveDevice"
	DaemonService_SetDeviceTags_FullMethodName = "/daemonrpc.DaemonService/SetDeviceTags"
	DaemonService_ApprovePeer_FullMethodName   = "/daemonrpc.DaemonService/ApprovePeer"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	StreamStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error)
	ResolveDevice(ctx context.Context, in *DeviceQuery, opts ...grpc.CallOption) (*DeviceAddress, error)
	SetDeviceTags(ctx context.Context, in *SetDeviceTagsRequest, opts ...grpc.CallOption) (*SetDeviceTagsResponse, error)
	ApprovePeer(ctx context.Context, in *ApprovePeerRequest, opts ...grpc.CallOption) (*ApprovePeerResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) StreamStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, StatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamStatusClient = grpc.ServerStreamingClient[StatusResponse]

func (c *daemonServiceClient) ResolveDevice(ctx context.Context, in *DeviceQuery, opts ...grpc.CallOption) (*DeviceAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceAddress)
	err := c.cc.Invoke(ctx, DaemonService_ResolveDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetDeviceTags(ctx context.Context, in *SetDeviceTagsRequest, opts ...grpc.CallOption) (*SetDeviceTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDeviceTagsResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetDeviceTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ApprovePeer(ctx context.Context, in *ApprovePeerRequest, opts ...grpc.CallOption) (*ApprovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePeerResponse)
	err := c.cc.Invoke(ctx, DaemonService_ApprovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	StreamStatus(*Empty, grpc.ServerStreamingServer[StatusResponse]) error
	ResolveDevice(context.Context, *DeviceQuery) (*DeviceAddress, error)
	SetDeviceTags(context.Context, *SetDeviceTagsRequest) (*SetDeviceTagsResponse, error)
	ApprovePeer(context.Context, *ApprovePeerRequest) (*ApprovePeerResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) StreamStatus(*Empty, grpc.ServerStreamingServer[StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedDaemonServiceServer) ResolveDevice(context.Context, *DeviceQuery) (*DeviceAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDevice not implemented")
}
func (UnimplementedDaemonServiceServer) SetDeviceTags(context.Context, *SetDeviceTagsRequest) (*SetDeviceTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeviceTags not implemented")
}
func (UnimplementedDaemonServiceServer) ApprovePeer(context.Context, *ApprovePeerRequest) (*ApprovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePeer not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamStatus(m, &grpc.GenericServerStream[Empty, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamStatusServer = grpc.ServerStreamingServer[StatusResponse]

func _DaemonService_ResolveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ResolveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ResolveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ResolveDevice(ctx, req.(*DeviceQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetDeviceTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetDeviceTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetDeviceTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetDeviceTags(ctx, req.(*SetDeviceTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ApprovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ApprovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ApprovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ApprovePeer(ctx, req.(*ApprovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemonrpc.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveDevice",
			Handler:    _DaemonService_ResolveDevice_Handler,
		},
		{
			MethodName: "SetDeviceTags",
			Handler:    _DaemonService_SetDeviceTags_Handler,
		},
		{
			MethodName: "ApprovePeer",
			Handler:    _DaemonService_ApprovePeer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _DaemonService_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/daemonrpc/proto/daemon.proto",
}
