// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: internal/daemonrpc/proto/daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaemonState    string                 `protobuf:"bytes,1,opt,name=daemon_state,json=daemonState,proto3" json:"daemon_state,omitempty"`
	DaemonVersion  string                 `protobuf:"bytes,2,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Generation     uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedAtUnix int64                  `protobuf:"varint,4,opt,name=observed_at_unix,json=observedAtUnix,proto3" json:"observed_at_unix,omitempty"`
	Peers          []*PeerStatus          `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	DerpRelays     []*DERPStatus          `protobuf:"bytes,6,rep,name=derp_relays,json=derpRelays,proto3" json:"derp_relays,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetDaemonState() string {
	if x != nil {
		return x.DaemonState
	}
	return ""
}

func (x *StatusResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *StatusResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *StatusResponse) GetObservedAtUnix() int64 {
	if x != nil {
		return x.ObservedAtUnix
	}
	return 0
}

func (x *StatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StatusResponse) GetDerpRelays() []*DERPStatus {
	if x != nil {
		return x.DerpRelays
	}
	return nil
}

type PeerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Alias          string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	AssignedIp     string                 `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	Online         bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ConnectionMode string                 `protobuf:"bytes,6,opt,name=connection_mode,json=connectionMode,proto3" json:"connection_mode,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Approved       bool                   `protobuf:"varint,8,opt,name=approved,proto3" json:"approved,omitempty"`
	ForwardedPorts []int32                `protobuf:"varint,9,rep,packed,name=forwarded_ports,json=forwardedPorts,proto3" json:"forwarded_ports,omitempty"`
	BrowserUrls    map[int32]string       `protobuf:"bytes,10,rep,name=browser_urls,json=browserUrls,proto3" json:"browser_urls,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *PeerStatus) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerStatus) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PeerStatus) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *PeerStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PeerStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerStatus) GetConnectionMode() string {
	if x != nil {
		return x.ConnectionMode
	}
	return ""
}

func (x *PeerStatus) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PeerStatus) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *PeerStatus) GetForwardedPorts() []int32 {
	if x != nil {
		return x.ForwardedPorts
	}
	return nil
}

func (x *PeerStatus) GetBrowserUrls() map[int32]string {
	if x != nil {
		return x.BrowserUrls
	}
	return nil
}

type DERPStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionCode    string                 `protobuf:"bytes,1,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	RegionName    string                 `protobuf:"bytes,2,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Reachable     bool                   `protobuf:"varint,3,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPStatus) Reset() {
	*x = DERPStatus{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPStatus) ProtoMessage() {}

func (x *DERPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPStatus.ProtoReflect.Descriptor instead.
func (*DERPStatus) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DERPStatus) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *DERPStatus) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *DERPStatus) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *DERPStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type DeviceQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceQuery) Reset() {
	*x = DeviceQuery{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceQuery) ProtoMessage() {}

func (x *DeviceQuery) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceQuery.ProtoReflect.Descriptor instead.
func (*DeviceQuery) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type DeviceAddress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Alias          string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	AssignedIp     string                 `protobuf:"bytes,3,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	ForwardedPorts []int32                `protobuf:"varint,4,rep,packed,name=forwarded_ports,json=forwardedPorts,proto3" json:"forwarded_ports,omitempty"`
	Tags           []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	BrowserUrls    map[int32]string       `protobuf:"bytes,6,rep,name=browser_urls,json=browserUrls,proto3" json:"browser_urls,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceAddress) Reset() {
	*x = DeviceAddress{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAddress) ProtoMessage() {}

func (x *DeviceAddress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAddress.ProtoReflect.Descriptor instead.
func (*DeviceAddress) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceAddress) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceAddress) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DeviceAddress) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *DeviceAddress) GetForwardedPorts() []int32 {
	if x != nil {
		return x.ForwardedPorts
	}
	return nil
}

func (x *DeviceAddress) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DeviceAddress) GetBrowserUrls() map[int32]string {
	if x != nil {
		return x.BrowserUrls
	}
	return nil
}

type SetDeviceTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceTagsRequest) Reset() {
	*x = SetDeviceTagsRequest{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceTagsRequest) ProtoMessage() {}

func (x *SetDeviceTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceTagsRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceTagsRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *SetDeviceTagsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetDeviceTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SetDeviceTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceTagsResponse) Reset() {
	*x = SetDeviceTagsResponse{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceTagsResponse) ProtoMessage() {}

func (x *SetDeviceTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceTagsResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceTagsResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *SetDeviceTagsResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetDeviceTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SetDeviceTagsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApprovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePeerRequest) Reset() {
	*x = ApprovePeerRequest{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePeerRequest) ProtoMessage() {}

func (x *ApprovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePeerRequest.ProtoReflect.Descriptor instead.
func (*ApprovePeerRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovePeerRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApprovePeerRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ApprovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePeerResponse) Reset() {
	*x = ApprovePeerResponse{}
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePeerResponse) ProtoMessage() {}

func (x *ApprovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemonrpc_proto_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePeerResponse.ProtoReflect.Descriptor instead.
func (*ApprovePeerResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovePeerResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApprovePeerResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_daemonrpc_proto_daemon_proto protoreflect.FileDescriptor

const file_internal_daemonrpc_proto_daemon_proto_rawDesc = "" +
	"\n" +
	"%internal/daemonrpc/proto/daemon.proto\x12\tdaemonrpc\"\a\n" +
	"\x05Empty\"\x89\x02\n" +
	"\x0eStatusResponse\x12!\n" +
	"\fdaemon_state\x18\x01 \x01(\tR\vdaemonState\x12%\n" +
	"\x0edaemon_version\x18\x02 \x01(\tR\rdaemonVersion\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12(\n" +
	"\x10observed_at_unix\x18\x04 \x01(\x03R\x0eobservedAtUnix\x12+\n" +
	"\x05peers\x18\x05 \x03(\v2\x15.daemonrpc.PeerStatusR\x05peers\x126\n" +
	"\vderp_relays\x18\x06 \x03(\v2\x15.daemonrpc.DERPStatusR\n" +
	"derpRelays\"\xa0\x03\n" +
	"\n" +
	"PeerStatus\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12'\n" +
	"\x0fconnection_mode\x18\x06 \x01(\tR\x0econnectionMode\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1a\n" +
	"\bapproved\x18\b \x01(\bR\bapproved\x12'\n" +
	"\x0fforwarded_ports\x18\t \x03(\x05R\x0eforwardedPorts\x12I\n" +
	"\fbrowser_urls\x18\n" +
	" \x03(\v2&.daemonrpc.PeerStatus.BrowserUrlsEntryR\vbrowserUrls\x1a>\n" +
	"\x10BrowserUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\n" +
	"DERPStatus\x12\x1f\n" +
	"\vregion_code\x18\x01 \x01(\tR\n" +
	"regionCode\x12\x1f\n" +
	"\vregion_name\x18\x02 \x01(\tR\n" +
	"regionName\x12\x1c\n" +
	"\treachable\x18\x03 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"#\n" +
	"\vDeviceQuery\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\xae\x02\n" +
	"\rDeviceAddress\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1f\n" +
	"\vassigned_ip\x18\x03 \x01(\tR\n" +
	"assignedIp\x12'\n" +
	"\x0fforwarded_ports\x18\x04 \x03(\x05R\x0eforwardedPorts\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12L\n" +
	"\fbrowser_urls\x18\x06 \x03(\v2).daemonrpc.DeviceAddress.BrowserUrlsEntryR\vbrowserUrls\x1a>\n" +
	"\x10BrowserUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14SetDeviceTagsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"b\n" +
	"\x15SetDeviceTagsResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"M\n" +
	"\x12ApprovePeerRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"h\n" +
	"\x13ApprovePeerResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xb3\x02\n" +
	"\rDaemonService\x12=\n" +
	"\fStreamStatus\x12\x10.daemonrpc.Empty\x1a\x19.daemonrpc.StatusResponse0\x01\x12A\n" +
	"\rResolveDevice\x12\x16.daemonrpc.DeviceQuery\x1a\x18.daemonrpc.DeviceAddress\x12R\n" +
	"\rSetDeviceTags\x12\x1f.daemonrpc.SetDeviceTagsRequest\x1a .daemonrpc.SetDeviceTagsResponse\x12L\n" +
	"\vApprovePeer\x12\x1d.daemonrpc.ApprovePeerRequest\x1a\x1e.daemonrpc.ApprovePeerResponseBDZBgithub.com/pinksaucepasta/paperboat/internal/daemonrpc/proto;protob\x06proto3"

var (
	file_internal_daemonrpc_proto_daemon_proto_rawDescOnce sync.Once
	file_internal_daemonrpc_proto_daemon_proto_rawDescData []byte
)

func file_internal_daemonrpc_proto_daemon_proto_rawDescGZIP() []byte {
	file_internal_daemonrpc_proto_daemon_proto_rawDescOnce.Do(func() {
		file_internal_daemonrpc_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_daemonrpc_proto_daemon_proto_rawDesc), len(file_internal_daemonrpc_proto_daemon_proto_rawDesc)))
	})
	return file_internal_daemonrpc_proto_daemon_proto_rawDescData
}

var file_internal_daemonrpc_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_daemonrpc_proto_daemon_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: daemonrpc.Empty
	(*StatusResponse)(nil),        // 1: daemonrpc.StatusResponse
	(*PeerStatus)(nil),            // 2: daemonrpc.PeerStatus
	(*DERPStatus)(nil),            // 3: daemonrpc.DERPStatus
	(*DeviceQuery)(nil),           // 4: daemonrpc.DeviceQuery
	(*DeviceAddress)(nil),         // 5: daemonrpc.DeviceAddress
	(*SetDeviceTagsRequest)(nil),  // 6: daemonrpc.SetDeviceTagsRequest
	(*SetDeviceTagsResponse)(nil), // 7: daemonrpc.SetDeviceTagsResponse
	(*ApprovePeerRequest)(nil),    // 8: daemonrpc.ApprovePeerRequest
	(*ApprovePeerResponse)(nil),   // 9: daemonrpc.ApprovePeerResponse
	nil,                           // 10: daemonrpc.PeerStatus.BrowserUrlsEntry
	nil,                           // 11: daemonrpc.DeviceAddress.BrowserUrlsEntry
}
var file_internal_daemonrpc_proto_daemon_proto_depIdxs = []int32{
	2,  // 0: daemonrpc.StatusResponse.peers:type_name -> daemonrpc.PeerStatus
	3,  // 1: daemonrpc.StatusResponse.derp_relays:type_name -> daemonrpc.DERPStatus
	10, // 2: daemonrpc.PeerStatus.browser_urls:type_name -> daemonrpc.PeerStatus.BrowserUrlsEntry
	11, // 3: daemonrpc.DeviceAddress.browser_urls:type_name -> daemonrpc.DeviceAddress.BrowserUrlsEntry
	0,  // 4: daemonrpc.DaemonService.StreamStatus:input_type -> daemonrpc.Empty
	4,  // 5: daemonrpc.DaemonService.ResolveDevice:input_type -> daemonrpc.DeviceQuery
	6,  // 6: daemonrpc.DaemonService.SetDeviceTags:input_type -> daemonrpc.SetDeviceTagsRequest
	8,  // 7: daemonrpc.DaemonService.ApprovePeer:input_type -> daemonrpc.ApprovePeerRequest
	1,  // 8: daemonrpc.DaemonService.StreamStatus:output_type -> daemonrpc.StatusResponse
	5,  // 9: daemonrpc.DaemonService.ResolveDevice:output_type -> daemonrpc.DeviceAddress
	7,  // 10: daemonrpc.DaemonService.SetDeviceTags:output_type -> daemonrpc.SetDeviceTagsResponse
	9,  // 11: daemonrpc.DaemonService.ApprovePeer:output_type -> daemonrpc.ApprovePeerResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_daemonrpc_proto_daemon_proto_init() }
func file_internal_daemonrpc_proto_daemon_proto_init() {
	if File_internal_daemonrpc_proto_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_daemonrpc_proto_daemon_proto_rawDesc), len(file_internal_daemonrpc_proto_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_daemonrpc_proto_daemon_proto_goTypes,
		DependencyIndexes: file_internal_daemonrpc_proto_daemon_proto_depIdxs,
		MessageInfos:      file_internal_daemonrpc_proto_daemon_proto_msgTypes,
	}.Build()
	File_internal_daemonrpc_proto_daemon_proto = out.File
	file_internal_daemonrpc_proto_daemon_proto_goTypes = nil
	file_internal_daemonrpc_proto_daemon_proto_depIdxs = nil
}
